from __future__ import annotations

from dataclasses import dataclass
import datetime as _datetime
import json
import os
from pathlib import Path
import re
import shutil
import tempfile
from typing import Iterable


TEMPLATE_SCHEMA_VERSION = 1


@dataclass(frozen=True, slots=True)
class ProjectTemplate:
    template_id: str
    label: str
    description: str
    default_language: str
    entry_file: str
    commands: dict[str, str]
    required_tools: tuple[str, ...]
    recommended_tools: tuple[str, ...]
    health_profile: str
    files: tuple[tuple[str, str], ...]


@dataclass(frozen=True, slots=True)
class ProjectTemplateResult:
    template: ProjectTemplate
    project_dir: Path
    config_path: Path
    entry_file: Path | None
    created_files: tuple[Path, ...]
    staffedup_metadata: dict[str, object]


_BASE_GITIGNORE = """# OS / editor\n.DS_Store\nThumbs.db\n.vscode/\n.idea/\n\n# Secrets and local state\n.env\n.env.*\n!.env.example\n*.local\n\n# Logs / temporary output\n*.log\n*.tmp\n*.swp\n\n# Astra Studio\n.astra-cache/\nPROJECT_CONTEXT.md\n"""

_WEB_GITIGNORE = _BASE_GITIGNORE + """\n# Node\nnode_modules/\ndist/\ncoverage/\n.vite/\n"""

_PYTHON_GITIGNORE = _BASE_GITIGNORE + """\n# Python\n.venv/\nvenv/\n__pycache__/\n*.py[cod]\n.pytest_cache/\n.mypy_cache/\n.ruff_cache/\n.coverage\nhtmlcov/\nbuild/\ndist/\n*.egg-info/\n"""

_GODOT_GITIGNORE = _BASE_GITIGNORE + """\n# Godot generated state\n.godot/\n.export/\nexport/\nbuild/\n"""

_ROBLOX_GITIGNORE = _BASE_GITIGNORE + """\n# Roblox / Rojo generated output\nbuild/\n*.rbxl\n*.rbxlx\n*.rbxm\n*.rbxmx\n"""


_WEB_PACKAGE_JSON = """{
  "name": "{{PROJECT_SLUG}}",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite --host 127.0.0.1",
    "build": "tsc -p tsconfig.json --noEmit && vite build",
    "test": "vitest run"
  },
  "devDependencies": {
    "@types/node": "latest",
    "typescript": "latest",
    "vite": "latest",
    "vitest": "latest"
  }
}
"""

_WEB_TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "noEmit": true,
    "skipLibCheck": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "types": ["vitest/globals"]
  },
  "include": ["src"]
}
"""


TEMPLATES: tuple[ProjectTemplate, ...] = (
    ProjectTemplate(
        template_id="web-typescript",
        label="Web / TypeScript",
        description="Современный TypeScript web-проект на Vite с тестовым контуром Vitest и StaffedUp-структурой.",
        default_language="TypeScript",
        entry_file="src/main.ts",
        commands={
            "run": "npm run dev",
            "build": "npm run build",
            "test": "npm run test",
            "install": "npm install",
        },
        required_tools=("node", "npm"),
        recommended_tools=("git",),
        health_profile="web-typescript",
        files=(
            ("package.json", _WEB_PACKAGE_JSON),
            ("tsconfig.json", _WEB_TSCONFIG),
            (".gitignore", _WEB_GITIGNORE),
            (".env.example", "# Public/client variables must be intentionally prefixed for your bundler.\n"),
            ("index.html", """<!doctype html>\n<html lang=\"ru\">\n<head>\n  <meta charset=\"UTF-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n  <title>{{PROJECT_NAME}}</title>\n</head>\n<body>\n  <main id=\"app\"></main>\n  <script type=\"module\" src=\"/src/main.ts\"></script>\n</body>\n</html>\n"""),
            ("src/main.ts", """import \"./styles.css\";\n\nconst app = document.querySelector<HTMLElement>(\"#app\");\n\nif (!app) {\n  throw new Error(\"#app root not found\");\n}\n\napp.innerHTML = `\n  <section class=\"card\">\n    <p class=\"eyebrow\">StaffedUp · Astra Studio</p>\n    <h1>{{PROJECT_NAME}}</h1>\n    <p>TypeScript starter is ready.</p>\n  </section>\n`;\n"""),
            ("src/styles.css", """* { box-sizing: border-box; }\nbody {\n  margin: 0;\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n  font-family: Inter, system-ui, sans-serif;\n  background: #101218;\n  color: #f5f7ff;\n}\n.card {\n  width: min(720px, calc(100vw - 32px));\n  padding: 32px;\n  border: 1px solid #313747;\n  border-radius: 20px;\n  background: #171b24;\n}\n.eyebrow { opacity: .65; }\n"""),
            ("src/main.test.ts", """import { describe, expect, it } from \"vitest\";\n\ndescribe(\"template\", () => {\n  it(\"starts with a working test runner\", () => {\n    expect(2 + 2).toBe(4);\n  });\n});\n"""),
            ("README.md", """# {{PROJECT_NAME}}\n\nStaffedUp Web / TypeScript template generated by Astra Studio.\n\n## Start\n\n1. Run **Install Project** in Astra Studio.\n2. Run **Run Project** for the Vite development server.\n3. Use **Build Project** before publishing and **Test Project** for Vitest.\n\nSecrets belong in `.env`, never in Git. Copy `.env.example` when environment variables are needed.\n"""),
            ("docs/README.md", """# Project documentation\n\nKeep architecture decisions, deployment notes and project-specific conventions here.\n"""),
        ),
    ),
    ProjectTemplate(
        template_id="yandex-games-typescript",
        label="Yandex Games / TypeScript",
        description="Browser-game skeleton with TypeScript, Vite, a local platform fallback and an isolated Yandex adapter boundary.",
        default_language="TypeScript",
        entry_file="src/main.ts",
        commands={
            "run": "npm run dev",
            "build": "npm run build",
            "test": "npm run test",
            "install": "npm install",
        },
        required_tools=("node", "npm"),
        recommended_tools=("git",),
        health_profile="yandex-games-typescript",
        files=(
            ("package.json", _WEB_PACKAGE_JSON),
            ("tsconfig.json", _WEB_TSCONFIG),
            (".gitignore", _WEB_GITIGNORE),
            ("index.html", """<!doctype html>\n<html lang=\"ru\">\n<head>\n  <meta charset=\"UTF-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n  <title>{{PROJECT_NAME}}</title>\n</head>\n<body>\n  <canvas id=\"game\" width=\"960\" height=\"540\" aria-label=\"Game canvas\"></canvas>\n  <script type=\"module\" src=\"/src/main.ts\"></script>\n</body>\n</html>\n"""),
            ("src/main.ts", """import \"./styles.css\";\nimport { startGame } from \"./game\";\nimport { createPlatform } from \"./platform\";\n\nasync function main(): Promise<void> {\n  const platform = await createPlatform();\n  await platform.ready();\n  startGame(platform);\n}\n\nvoid main();\n"""),
            ("src/game.ts", """import type { GamePlatform } from \"./platform/types\";\n\nexport function startGame(platform: GamePlatform): void {\n  const canvas = document.querySelector<HTMLCanvasElement>(\"#game\");\n  if (!canvas) throw new Error(\"Game canvas not found\");\n  const context = canvas.getContext(\"2d\");\n  if (!context) throw new Error(\"2D context unavailable\");\n\n  context.fillStyle = \"#111827\";\n  context.fillRect(0, 0, canvas.width, canvas.height);\n  context.fillStyle = \"#f8fafc\";\n  context.font = \"32px system-ui\";\n  context.fillText(\"{{PROJECT_NAME}}\", 48, 72);\n  context.font = \"18px system-ui\";\n  context.fillText(`Platform: ${platform.kind}`, 48, 112);\n}\n"""),
            ("src/platform/types.ts", """export interface GamePlatform {\n  readonly kind: \"local\" | \"yandex\";\n  ready(): Promise<void>;\n}\n"""),
            ("src/platform/local.ts", """import type { GamePlatform } from \"./types\";\n\nexport const localPlatform: GamePlatform = {\n  kind: \"local\",\n  async ready() {\n    return;\n  },\n};\n"""),
            ("src/platform/yandex.ts", """import type { GamePlatform } from \"./types\";\n\ntype YaGamesLike = { init: () => Promise<unknown> };\n\nexport function hasYandexSdk(): boolean {\n  const candidate = (globalThis as { YaGames?: YaGamesLike }).YaGames;\n  return typeof candidate?.init === \"function\";\n}\n\nexport const yandexPlatform: GamePlatform = {\n  kind: \"yandex\",\n  async ready() {\n    const sdk = (globalThis as { YaGames?: YaGamesLike }).YaGames;\n    if (!sdk) throw new Error(\"Yandex Games SDK is unavailable\");\n    await sdk.init();\n  },\n};\n"""),
            ("src/platform/index.ts", """import type { GamePlatform } from \"./types\";\nimport { localPlatform } from \"./local\";\nimport { hasYandexSdk, yandexPlatform } from \"./yandex\";\n\nexport async function createPlatform(): Promise<GamePlatform> {\n  return hasYandexSdk() ? yandexPlatform : localPlatform;\n}\n"""),
            ("src/platform/local.test.ts", """import { describe, expect, it } from \"vitest\";\nimport { localPlatform } from \"./local\";\n\ndescribe(\"local platform\", () => {\n  it(\"is available without platform SDK\", async () => {\n    await localPlatform.ready();\n    expect(localPlatform.kind).toBe(\"local\");\n  });\n});\n"""),
            ("src/styles.css", """html, body { margin: 0; min-height: 100%; background: #090d16; color: white; }\nbody { min-height: 100vh; display: grid; place-items: center; }\n#game { width: min(100vw, 960px); height: auto; background: #111827; }\n"""),
            ("README.md", """# {{PROJECT_NAME}}\n\nStaffedUp Yandex Games / TypeScript starter. The game logic is separated from platform integration so local development can use a deterministic mock boundary.\n\n## Start\n\n1. **Install Project** installs the local TypeScript/Vite toolchain.\n2. **Run Project** starts local development. Without a Yandex SDK object the local adapter is used.\n3. Before platform publication, wire the official Yandex Games SDK according to the current platform documentation and keep SDK-specific calls inside `src/platform/`.\n4. **Build Project** produces `dist/`.\n\nDo not put platform secrets or private credentials in the browser bundle.\n"""),
            ("docs/PLATFORM.md", """# Platform boundary\n\n- `src/game.ts` contains game behavior independent of the host platform.\n- `src/platform/local.ts` is the local fallback.\n- `src/platform/yandex.ts` is the only place intended for Yandex-specific SDK calls.\n\nVerify current platform publishing requirements before release; they can change independently of this template.\n"""),
        ),
    ),
    ProjectTemplate(
        template_id="roblox-luau",
        label="Roblox / Luau",
        description="Rojo-based Roblox skeleton with separated client/server/shared code and no generated binary assets in Git.",
        default_language="Luau",
        entry_file="src/server/init.server.luau",
        commands={
            "run": "{rojo} serve default.project.json",
            "build": "{rojo} build default.project.json -o game.rbxlx",
            "test": "",
            "install": "",
        },
        required_tools=("rojo",),
        recommended_tools=("git", "luau-analyze"),
        health_profile="roblox-luau",
        files=(
            (".gitignore", _ROBLOX_GITIGNORE),
            ("default.project.json", """{\n  \"name\": \"{{PROJECT_NAME}}\",\n  \"tree\": {\n    \"$className\": \"DataModel\",\n    \"ReplicatedStorage\": {\n      \"Shared\": {\n        \"$path\": \"src/shared\"\n      }\n    },\n    \"ServerScriptService\": {\n      \"Server\": {\n        \"$path\": \"src/server\"\n      }\n    },\n    \"StarterPlayer\": {\n      \"StarterPlayerScripts\": {\n        \"Client\": {\n          \"$path\": \"src/client\"\n        }\n      }\n    }\n  }\n}\n"""),
            ("src/shared/Config.luau", """local Config = {\n    ProjectName = \"{{PROJECT_NAME}}\",\n}\n\nreturn table.freeze(Config)\n"""),
            ("src/server/init.server.luau", """local ReplicatedStorage = game:GetService(\"ReplicatedStorage\")\nlocal Config = require(ReplicatedStorage.Shared.Config)\n\nprint((\"%s server started\"):format(Config.ProjectName))\n"""),
            ("src/client/init.client.luau", """local ReplicatedStorage = game:GetService(\"ReplicatedStorage\")\nlocal Config = require(ReplicatedStorage.Shared.Config)\n\nprint((\"%s client started\"):format(Config.ProjectName))\n"""),
            ("README.md", """# {{PROJECT_NAME}}\n\nStaffedUp Roblox / Luau template.\n\n- `src/server` — server-only code.\n- `src/client` — client-only code.\n- `src/shared` — replicated shared modules/data.\n- `default.project.json` — Rojo mapping.\n\nUse **Run Project** to start `rojo serve` and **Build Project** to create `game.rbxlx`. Astra does not install Rojo silently.\n"""),
            ("docs/ARCHITECTURE.md", """# Architecture\n\nKeep trust boundaries explicit: validation and authoritative game state belong on the server; presentation/input belong on the client; only genuinely shared modules belong in `src/shared`.\n"""),
        ),
    ),
    ProjectTemplate(
        template_id="godot",
        label="Godot / GDScript",
        description="Minimal Godot 4 project with a real scene, script boundary and generated `.godot` state excluded from Git.",
        default_language="GDScript",
        entry_file="scripts/main.gd",
        commands={
            "run": "{godot} --path .",
            "build": "",
            "test": "",
            "install": "",
        },
        required_tools=("godot",),
        recommended_tools=("git",),
        health_profile="godot",
        files=(
            (".gitignore", _GODOT_GITIGNORE),
            ("project.godot", """; Engine configuration file.\n; Generated by Astra Studio StaffedUp template.\nconfig_version=5\n\n[application]\nconfig/name=\"{{PROJECT_NAME}}\"\nrun/main_scene=\"res://scenes/main.tscn\"\n\n[display]\nwindow/size/viewport_width=960\nwindow/size/viewport_height=540\nwindow/size/window_width_override=960\nwindow/size/window_height_override=540\n\n[rendering]\nrenderer/rendering_method=\"gl_compatibility\"\nrenderer/rendering_method.mobile=\"gl_compatibility\"\n"""),
            ("scenes/main.tscn", """[gd_scene load_steps=2 format=3]\n\n[ext_resource path=\"res://scripts/main.gd\" type=\"Script\" id=\"1_main\"]\n\n[node name=\"Main\" type=\"Node2D\"]\nscript = ExtResource(\"1_main\")\n\n[node name=\"Title\" type=\"Label\" parent=\".\"]\nposition = Vector2(32, 32)\ntext = \"{{PROJECT_NAME}}\"\n"""),
            ("scripts/main.gd", """extends Node2D\n\nfunc _ready() -> void:\n    print(\"{{PROJECT_NAME}} started\")\n"""),
            ("README.md", """# {{PROJECT_NAME}}\n\nStaffedUp Godot 4 / GDScript starter.\n\nUse **Run Project** to start Godot from the project directory. Export presets are intentionally not guessed by the template because target platform credentials/SDK requirements are project-specific.\n"""),
            ("docs/ARCHITECTURE.md", """# Architecture\n\nKeep reusable gameplay code under `scripts/` and scene composition under `scenes/`. Add platform/export notes here when the project target is fixed.\n"""),
        ),
    ),
    ProjectTemplate(
        template_id="python-app",
        label="Python App",
        description="Python application package with standard-library tests and project-local environment support.",
        default_language="Python",
        entry_file="app/__main__.py",
        commands={
            "run": "{python} -m app",
            "build": "",
            "test": "{python} -m unittest discover -s tests -v",
            "install": "{python-deps}",
        },
        required_tools=("python",),
        recommended_tools=("uv", "git"),
        health_profile="python-app",
        files=(
            (".gitignore", _PYTHON_GITIGNORE),
            ("pyproject.toml", """[build-system]\nrequires = [\"setuptools>=68\"]\nbuild-backend = \"setuptools.build_meta\"\n\n[project]\nname = \"{{PROJECT_SLUG}}\"\nversion = \"0.1.0\"\ndescription = \"{{PROJECT_NAME}}\"\nrequires-python = ">=3.11"\ndependencies = []\n\n[tool.setuptools]\npackages = [\"app\"]\n"""),
            ("app/__init__.py", """\"\"\"{{PROJECT_NAME}} package.\"\"\"\n"""),
            ("app/__main__.py", """from __future__ import annotations\n\n\ndef main() -> None:\n    print(\"{{PROJECT_NAME}} is ready\")\n\n\nif __name__ == \"__main__\":\n    main()\n"""),
            ("tests/test_smoke.py", """from __future__ import annotations\n\nimport unittest\n\n\nclass SmokeTests(unittest.TestCase):\n    def test_math(self) -> None:\n        self.assertEqual(2 + 2, 4)\n\n\nif __name__ == \"__main__\":\n    unittest.main()\n"""),
            ("README.md", """# {{PROJECT_NAME}}\n\nStaffedUp Python application template.\n\n1. Create/select a project `.venv` in Astra Studio.\n2. **Install Project** installs the local package/dependencies.\n3. **Run Project** starts `python -m app`.\n4. **Test Project** uses only the standard library by default.\n"""),
            ("docs/ARCHITECTURE.md", """# Architecture\n\nApplication code lives in the `app/` package so `python -m app` works immediately from the project root while the same package can still be installed from `pyproject.toml`.\n"""),
        ),
    ),
    ProjectTemplate(
        template_id="telegram-bot",
        label="Telegram Bot / Python",
        description="Python Telegram bot skeleton with token isolation, `.env.example`, aiogram 3 and testable config code.",
        default_language="Python",
        entry_file="bot.py",
        commands={
            "run": "{python} bot.py",
            "build": "",
            "test": "{python} -m unittest discover -s tests -v",
            "install": "{python-deps}",
        },
        required_tools=("python",),
        recommended_tools=("uv", "git"),
        health_profile="telegram-bot",
        files=(
            (".gitignore", _PYTHON_GITIGNORE),
            (".env.example", "TELEGRAM_BOT_TOKEN=replace-me\n"),
            ("requirements.txt", "aiogram>=3,<4\npython-dotenv>=1,<2\n"),
            ("app/__init__.py", ""),
            ("app/config.py", """from __future__ import annotations\n\nimport os\n\n\ndef telegram_token() -> str:\n    token = os.getenv(\"TELEGRAM_BOT_TOKEN\", \"\").strip()\n    if not token:\n        raise RuntimeError(\"TELEGRAM_BOT_TOKEN is not configured\")\n    return token\n"""),
            ("bot.py", """from __future__ import annotations\n\nimport asyncio\n\nfrom aiogram import Bot, Dispatcher\nfrom aiogram.filters import CommandStart\nfrom aiogram.types import Message\nfrom dotenv import load_dotenv\n\nfrom app.config import telegram_token\n\n\ndp = Dispatcher()\n\n\n@dp.message(CommandStart())\nasync def start(message: Message) -> None:\n    await message.answer(\"{{PROJECT_NAME}} is online\")\n\n\nasync def main() -> None:\n    load_dotenv()\n    bot = Bot(token=telegram_token())\n    await dp.start_polling(bot)\n\n\nif __name__ == \"__main__\":\n    asyncio.run(main())\n"""),
            ("tests/test_config.py", """from __future__ import annotations\n\nimport os\nimport unittest\nfrom unittest.mock import patch\n\nfrom app.config import telegram_token\n\n\nclass ConfigTests(unittest.TestCase):\n    def test_missing_token_is_rejected(self) -> None:\n        with patch.dict(os.environ, {}, clear=True):\n            with self.assertRaises(RuntimeError):\n                telegram_token()\n\n    def test_token_is_read_from_environment(self) -> None:\n        with patch.dict(os.environ, {\"TELEGRAM_BOT_TOKEN\": \"demo\"}, clear=True):\n            self.assertEqual(telegram_token(), \"demo\")\n\n\nif __name__ == \"__main__\":\n    unittest.main()\n"""),
            ("README.md", """# {{PROJECT_NAME}}\n\nStaffedUp Telegram Bot starter.\n\n1. Copy `.env.example` to `.env` and put the real bot token only in `.env`.\n2. Create/select a project `.venv`.\n3. Run **Install Project**.\n4. Run **Test Project** and then **Run Project**.\n\n`.env` is ignored by Git. Never commit the real token.\n"""),
            ("docs/ARCHITECTURE.md", """# Architecture\n\nKeep secrets/config loading independent from Telegram handlers so it can be tested without starting a network client. Add handlers/services as separate modules under `app/`.\n"""),
        ),
    ),
    ProjectTemplate(
        template_id="static-website",
        label="Static Website",
        description="Dependency-free HTML/CSS/JavaScript site with a tiny local server command and no frontend build step.",
        default_language="HTML",
        entry_file="index.html",
        commands={
            "run": "{python} -m http.server 8000",
            "build": "",
            "test": "",
            "install": "",
        },
        required_tools=("python",),
        recommended_tools=("git",),
        health_profile="static-website",
        files=(
            (".gitignore", _BASE_GITIGNORE),
            ("index.html", """<!doctype html>\n<html lang=\"ru\">\n<head>\n  <meta charset=\"UTF-8\" />\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n  <title>{{PROJECT_NAME}}</title>\n  <link rel=\"stylesheet\" href=\"styles.css\" />\n</head>\n<body>\n  <main class=\"container\">\n    <h1>{{PROJECT_NAME}}</h1>\n    <p>Static StaffedUp starter generated by Astra Studio.</p>\n  </main>\n  <script src=\"script.js\"></script>\n</body>\n</html>\n"""),
            ("styles.css", """* { box-sizing: border-box; }\nbody { margin: 0; font-family: system-ui, sans-serif; background: #0f1117; color: #f7f7fb; }\n.container { width: min(960px, calc(100% - 32px)); margin: 64px auto; }\n"""),
            ("script.js", """console.log(\"{{PROJECT_NAME}} ready\");\n"""),
            ("README.md", """# {{PROJECT_NAME}}\n\nDependency-free StaffedUp static website template. Open `index.html` directly or use **Run Project** when Python is available to serve the folder on port 8000.\n"""),
            ("docs/README.md", """# Project documentation\n\nKeep publishing/domain/content notes here.\n"""),
        ),
    ),
    ProjectTemplate(
        template_id="empty",
        label="Empty Project",
        description="Clean StaffedUp project shell: project config, README and safe `.gitignore`, without invented runtime dependencies.",
        default_language="Markdown",
        entry_file="README.md",
        commands={"run": "", "build": "", "test": "", "install": ""},
        required_tools=(),
        recommended_tools=("git",),
        health_profile="empty",
        files=(
            (".gitignore", _BASE_GITIGNORE),
            ("README.md", """# {{PROJECT_NAME}}\n\nEmpty StaffedUp project generated by Astra Studio.\n\nAdd only the architecture and dependencies the project actually needs.\n"""),
            ("docs/README.md", """# Project documentation\n\nArchitecture, decisions and operational notes can be recorded here as the project grows.\n"""),
        ),
    ),
)


_TEMPLATE_BY_ID = {template.template_id: template for template in TEMPLATES}


_CYRILLIC_MAP = str.maketrans(
    {
        "а": "a", "б": "b", "в": "v", "г": "g", "д": "d", "е": "e", "ё": "e", "ж": "zh",
        "з": "z", "и": "i", "й": "y", "к": "k", "л": "l", "м": "m", "н": "n", "о": "o",
        "п": "p", "р": "r", "с": "s", "т": "t", "у": "u", "ф": "f", "х": "h", "ц": "ts",
        "ч": "ch", "ш": "sh", "щ": "sch", "ъ": "", "ы": "y", "ь": "", "э": "e", "ю": "yu", "я": "ya",
    }
)


def project_slug(project_name: str) -> str:
    raw = str(project_name or "").strip().lower().translate(_CYRILLIC_MAP)
    slug = re.sub(r"[^a-z0-9]+", "-", raw).strip("-")
    return slug or "staffedup-project"


def python_package_name(project_name: str) -> str:
    slug = project_slug(project_name).replace("-", "_")
    slug = re.sub(r"[^a-z0-9_]", "_", slug)
    if not slug or slug[0].isdigit():
        slug = f"app_{slug or 'project'}"
    return slug


def get_project_template(template_id: str) -> ProjectTemplate:
    try:
        return _TEMPLATE_BY_ID[str(template_id)]
    except KeyError as exc:
        raise KeyError(f"Unknown Astra project template: {template_id}") from exc


def project_template_choices() -> tuple[tuple[str, str], ...]:
    return tuple((template.template_id, template.label) for template in TEMPLATES)


def _render(text: str, project_name: str) -> str:
    replacements = {
        "{{PROJECT_NAME}}": project_name,
        "{{PROJECT_SLUG}}": project_slug(project_name),
        "{{PYTHON_PACKAGE}}": python_package_name(project_name),
    }
    rendered = str(text)
    for token, value in replacements.items():
        rendered = rendered.replace(token, value)
    return rendered


def _validated_relative_path(raw: str, project_name: str) -> Path:
    rendered = _render(raw, project_name).replace("\\", "/")
    path = Path(rendered)
    if path.is_absolute() or ".." in path.parts or not path.parts:
        raise ValueError(f"Unsafe project template path: {raw}")
    return path


def rendered_template_files(template_id: str, project_name: str) -> dict[Path, str]:
    template = get_project_template(template_id)
    files: dict[Path, str] = {}
    for raw_path, raw_text in template.files:
        path = _validated_relative_path(raw_path, project_name)
        if path in files:
            raise ValueError(f"Duplicate template path: {path}")
        files[path] = _render(raw_text, project_name)
    return files


def staffedup_metadata(template: ProjectTemplate) -> dict[str, object]:
    return {
        "template": template.template_id,
        "templateVersion": TEMPLATE_SCHEMA_VERSION,
        "healthProfile": template.health_profile,
        "requiredTools": list(template.required_tools),
        "recommendedTools": list(template.recommended_tools),
    }


def _initial_project_config(template: ProjectTemplate, project_name: str, astra_version: str) -> dict[str, object]:
    entry = _render(template.entry_file, project_name) if template.entry_file else ""
    commands = {key: _render(template.commands.get(key, ""), project_name) for key in ("run", "build", "test", "install")}
    return {
        "projectName": project_name,
        "version": str(astra_version).replace("Release ", ""),
        "createdAt": _datetime.datetime.now().isoformat(timespec="seconds"),
        "mainFolder": ".",
        "attachedFolders": [],
        "openFiles": [entry] if entry else [],
        "activeFile": entry,
        "defaultLanguage": template.default_language,
        "pythonInterpreter": "",
        "commands": commands,
        "testExplorerLastRun": None,
        "settings": {
            "tabSize": 4,
            "indentSize": 4,
            "insertSpaces": True,
            "uiFontSize": 13,
            "editorFontSize": 12,
            "consoleFontSize": 10,
        },
        "staffedUp": staffedup_metadata(template),
        "astralStudioVersion": astra_version,
    }


def _ensure_target_is_available(target: Path) -> None:
    if not target.exists():
        return
    if not target.is_dir():
        raise FileExistsError(f"Project target exists and is not a directory: {target}")
    try:
        next(target.iterdir())
    except StopIteration:
        return
    raise FileExistsError(f"Project folder is not empty: {target}")


def create_project_from_template(target_dir: Path, project_name: str, template_id: str, astra_version: str) -> ProjectTemplateResult:
    """Create a complete project skeleton without invoking package managers or the network.

    Files are assembled in a sibling staging directory and moved into place only
    after the whole template has been rendered successfully. Existing non-empty
    folders are never overwritten.
    """

    project_name = str(project_name or "").strip()
    if not project_name:
        raise ValueError("Project name must not be empty")
    target = Path(target_dir)
    parent = target.parent
    parent.mkdir(parents=True, exist_ok=True)
    _ensure_target_is_available(target)

    template = get_project_template(template_id)
    files = rendered_template_files(template.template_id, project_name)
    config = _initial_project_config(template, project_name, astra_version)

    staging: Path | None = Path(tempfile.mkdtemp(prefix=".astra-project-", dir=str(parent)))
    try:
        created_rel: list[Path] = []
        for relative, content in files.items():
            destination = staging / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8", newline="\n")
            created_rel.append(relative)

        config_rel = Path("astral.project.json")
        (staging / config_rel).write_text(json.dumps(config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
        created_rel.append(config_rel)

        # A pre-existing empty target can be safely replaced. A non-empty target
        # was rejected above and is never touched.
        if target.exists():
            target.rmdir()
        os.replace(staging, target)
        staging = None

        entry_relative = Path(_render(template.entry_file, project_name)) if template.entry_file else None
        entry_path = target / entry_relative if entry_relative else None
        return ProjectTemplateResult(
            template=template,
            project_dir=target,
            config_path=target / config_rel,
            entry_file=entry_path if entry_path and entry_path.is_file() else None,
            created_files=tuple(target / rel for rel in created_rel),
            staffedup_metadata=staffedup_metadata(template),
        )
    finally:
        if staging is not None and staging.exists():
            shutil.rmtree(staging, ignore_errors=True)
